#!/bin/bash
set -euo pipefail

TIMESTAMP=$(date "+%F_%T.%N")
DEBUG_LOG=/var/log/receiver."$TIMESTAMP".debug.log
STDOUT_LOG=/var/log/receiver."$TIMESTAMP".stdout.log

EXE=$(which cvmfs_receiver_debug)
if [[ "$EXE" == '' ]]; then
	EXE=$(which cvmfs_receiver)
fi

#exec rr "$EXE" "$@" -d "$DEBUG_LOG" &> "$STDOUT_LOG"
exec "$EXE" "$@" -d "$DEBUG_LOG" &> "$STDOUT_LOG"
