#!/bin/bash
cvmfs_test_name="Mountless repository gateway ingest: parallel stress test"
cvmfs_test_autofs_on_startup=false
cvmfs_test_suites="quick"


produce_tarball() {
  local tarball_name=$(readlink -f "$1")
  mkdir empty
  pushd empty
  tar -cf "$tarball_name" .
  popd
  rm -rf empty
}


cvmfs_run_test() {
  local repo="test.repo.org"
  local tarfile="$(pwd)/tarball.tar"

  set_up_repository_gateway -P || return 1
  load_repo_config "$repo" || return 2

  echo "*** check bootstrap leaves the repository unmounted"
  cat /proc/mounts | grep -e " /cvmfs/${repo} " && return 3
  cat /proc/mounts | grep -e " ${CVMFS_SPOOL_DIR}/rdonly " && return 4

  produce_tarball "$tarfile" || return 10

  echo "*** ingest tarball without a publisher mount"
  local n=10
  DIRS_CERATED=()
  for i in $(seq 1 $n); do
    dir=$(printf %05d $i)
    DIRS_CREATED+=("$dir")
    cvmfs_server ingest --tar_file "$tarfile" --base_dir "$dir" "$repo"  &
  done
  wait

  echo "*** mountless ingest should not remount the publisher view"
  cat /proc/mounts | grep -e " /cvmfs/${repo} " && return 21
  cat /proc/mounts | grep -e " ${CVMFS_SPOOL_DIR}/rdonly " && return 22
  [ ! -f ${CVMFS_SPOOL_DIR}/session_token ] || return 23

  echo "*** verify published ingest artifacts without remounting the publisher view"

  cvmfs_server check -i "$repo"
  check_repo_integrity "$repo"

  sudo mount "$CVMFS_SPOOL_DIR"/rdonly
  DIRS_PRESENT=( $(ls "$CVMFS_SPOOL_DIR"/rdonly) )
  for i in $(seq 0 $(( n - 1 )) ); do
    [[ ${DIRS_CREATED[$i]} == ${DIRS_PRESENT[$i]} ]]
  done

}
