#!/bin/bash
set -euo pipefail
set -x

mkdir -p /var/{spool,run}/cvmfs/
[[ -d /etc/cvmfs/default.d ]]
[[ "$(whoami)" == root ]]
echo CVMFS_HTTP_PROXY=DIRECT | sudo tee /etc/cvmfs/default.d/98-proxy-direct.conf
echo CVMFS_USER=$(whoami) | sudo tee /etc/cvmfs/default.d/98-user.conf
export CVMFS_TEST_USER=$(whoami)
export CVMFS_TEST_PROXY=DIRECT
[[ -v TEST_ROOT ]] # expected /home/sftnight/cvmfs/test
this_script_dir=$TEST_ROOT/src/901-ingestsql
build_dir=$(dirname "$TEST_ROOT")
: ${CVMFS_TEST_REPO:=test.repo}
: ${CVMFS_TEST_MOUNTPOINT:=/tmp/ingestsql_test_mount}
export DEBUG
CVMFS2=cvmfs2
if [[ -v DEBUG ]]; then
    CVMFS2="$this_script_dir"/cvmfs2-wrapper
    export CVMFS_SERVER_DEBUG=1
fi

rsyslogd &

sudo mkdir -p /var/http/root/"$CVMFS_TEST_REPO"/"$CVMFS_TEST_REPO"
sudo touch             /var/log/small-proxyd.log /var/log/small-httpd.log /var/log/gateway.log
sudo chown "$(whoami)" /var/log/small-proxyd.log /var/log/small-httpd.log /var/log/gateway.log
! fuser -n tcp 8088
stdbuf -i0 -o0 -e0  "$this_script_dir"/opt/bin/proxy_server.py     &> /var/log/small-proxyd.log &
! fuser -n tcp 8000
stdbuf -i0 -o0 -e0  "$this_script_dir"/opt/bin/http_server.py 8000 &> /var/log/small-httpd.log  &
http_ports_up() {
    fuser -n tcp 8088 && fuser -n tcp 8000
}
for seconds in {1..10}; do
    if http_ports_up; then break; fi
    sleep 1
done
http_ports_up

run_gateway() {
    while true; do
        MAYBE_TRACER=''
        RECEIVER=$(which cvmfs_receiver)
        if [[ -v DEBUG ]]; then
            MAYBE_TRACER=rr
            RECEIVER="$this_script_dir/receiver-wrapper"
        fi
        $MAYBE_TRACER cvmfs_gateway --access_config_file /etc/cvmfs/gateway/"$CVMFS_TEST_REPO"/repo.json --user_config_file /etc/cvmfs/gateway/"$CVMFS_TEST_REPO"/user.json --work_dir /var/lib/cvmfs-gateway/"$CVMFS_TEST_REPO" --receiver_path "$RECEIVER" &>> /var/log/gateway.log
    done
}
sudo rsync -rtv "$this_script_dir"/etc/cvmfs/gateway  /etc/cvmfs
sudo rsync -rtv "$this_script_dir"/etc/cvmfs/config.d /etc/cvmfs
sudo rsync -rtv "$this_script_dir"/etc/cvmfs-gateway-client  /etc
run_gateway &
gateway_up() {
    fuser -n tcp 4929
}
# wait for the backgrounded httpd, proxyd, gateway to boot up
for seconds in {1..10}; do
    if gateway_up; then break; fi
    sleep 1
done
gateway_up


echo user_allow_other | sudo tee -a /etc/fuse.conf

if [[ -v RECONSTRUCT_REPO ]]; then
    # This code is not executed by default.
    # This code is incomplete.
    # There is no code to reconstruct the files checked in graft-tests.py:do_file_read_test().
    # Works only under systemd.
    systemctl start httpd
    cvmfs_server mkfs -o "$CVMFS_TEST_USER" -w http://127.0.0.1:8000/"$CVMFS_TEST_REPO" -s "$this_script_dir"/etc/cvmfs/repositories.d/test.repo/s3.conf "$CVMFS_TEST_REPO"
    cp /etc/cvmfs/keys/"$CVMFS_TEST_REPO".pub /etc/cvmfs-gateway-client/"$CVMFS_TEST_REPO"/pubkey

    cvmfs_server transaction "$MY_REPO"
    mkdir -p /cvmfs/"$MY_REPO"/TEST_DIRECTORY/DIR{1,2,3}
    for subdir in . DIR{1,2,3}; do
        for file in /cvmfs/"$MY_REPO"/TEST_DIRECTORY/"$subdir"/file{1,2,3}; do
        echo OH HI > "$file"
        done
    done
    cvmfs_server publish "$MY_REPO"
    cvmfs_config umount # or: fusermount -u /var/spool/cvmfs/"$MY_REPO"/rdonly
    umount /cvmfs/$MY_REPO

else # ! [[ -v RECONSTRUCT_REPO ]]
    sudo rsync -rtv "$this_script_dir"/var/spool/cvmfs/test.repo/  /var/spool/cvmfs/"$CVMFS_TEST_REPO"
    sudo rsync -rtv "$this_script_dir"/var/http/root/test.repo/test.repo/  /var/http/root/"$CVMFS_TEST_REPO"/"$CVMFS_TEST_REPO"
    sudo rsync -rtv "$this_script_dir"/etc/cvmfs/{repositories.d,keys}  /etc/cvmfs
fi

mkdir -p "$CVMFS_TEST_MOUNTPOINT"
# TODO The manifest file .cvmfspublished file contains test.repo as repo name, needs changing and re-signing for parametrized $CVMFS_TEST_REPO.
# Check that HTTP servers serve expected contents:
diff -Nurd /var/http/root/"$CVMFS_TEST_REPO"/"$CVMFS_TEST_REPO"/.cvmfspublished <(curl --disable --fail http://localhost:8000/$CVMFS_TEST_REPO/$CVMFS_TEST_REPO/.cvmfspublished)
diff -Nurd /var/http/root/"$CVMFS_TEST_REPO"/"$CVMFS_TEST_REPO"/.cvmfspublished <(curl --disable --fail --proxy http://localhost:8088 http://localhost:8000/$CVMFS_TEST_REPO/$CVMFS_TEST_REPO/.cvmfspublished)

"$CVMFS2" -d -o config=/etc/cvmfs/repositories.d/$CVMFS_TEST_REPO/client.conf,allow_other $CVMFS_TEST_REPO "$CVMFS_TEST_MOUNTPOINT" &>> /var/log/cvmfs2.log
attr -g revision "$CVMFS_TEST_MOUNTPOINT" # a check of mount success
ls -l "$CVMFS_TEST_MOUNTPOINT"
[[ -f "$CVMFS_TEST_MOUNTPOINT"/TEST_DIRECTORY/DIR1/file1 ]]

export PYTHONUNBUFFERED=1
#"$this_script_dir"/graft-tests.py --no-mount standard file-read |& tee /var/log/graft-tests.log
"$this_script_dir"/graft-tests.py --no-mount standard |& tee /var/log/graft-tests.log
