#!/bin/bash
set -euo pipefail
set -x

sudo mkdir -p /var/{spool,run}/cvmfs/
[[ -d /etc/cvmfs/default.d ]]
echo CVMFS_HTTP_PROXY=DIRECT | sudo tee /etc/cvmfs/default.d/98-proxy-direct.conf
echo CVMFS_USER=$(whoami) | sudo tee /etc/cvmfs/default.d/98-user.conf
export CVMFS_TEST_USER=$(whoami)
export CVMFS_TEST_PROXY=DIRECT
[[ -v TEST_ROOT ]] # expected /home/sftnight/cvmfs/test
this_script_dir=$TEST_ROOT/src/901-ingestsql
build_dir=$(dirname "$TEST_ROOT")
: ${CVMFS_TEST_REPO:=test.repo}
: ${CVMFS_TEST_MOUNTPOINT:=/tmp/ingestsql_test_mount}
#export DEBUG=1
CVMFS2=cvmfs2
if [[ -v DEBUG ]]; then
    CVMFS2="$this_script_dir"/cvmfs2-wrapper
    export CVMFS_SERVER_DEBUG=3
fi

rsyslogd &

http_ports_up() {
    sudo fuser -n tcp 8088 && sudo fuser -n tcp 8000
}

if [[ -v CVMFS_TEST_S3_CONFIG ]]; then
    S3_SERVER_PROVIDED=1
    source "$CVMFS_TEST_S3_CONFIG"
    S3_HOST=${CVMFS_S3_HOST%:*}
    S3_PORT=${CVMFS_S3_HOST#*:}
    S3_WEB_HOST=cvmfs.web.garage.internal
    S3_WEB_PORT=3902
    # TODO upload data into garage
    sudo tee ~/.s3cfg <<-EOF
host_base = $CVMFS_S3_HOST
host_bucket = $S3_HOST:$S3_PORT
use_https = False
access_key = $CVMFS_S3_ACCESS_KEY
secret_key = $CVMFS_S3_SECRET_KEY
EOF
else
    false
#    S3_SERVER_PROVIDED=0
#    S3_HOST=127.0.0.1
#    S3_PORT=8000
#    S3_WEB_HOST=127.0.0.1
#    S3_WEB_PORT=8000
#    export CVMFS_TEST_HTTP_BASE=http://127.0.0.1:8000/"$CVMFS_TEST_REPO"
#    sudo mkdir -p /shared
#    CVMFS_TEST_S3_CONFIG=/shared/test_s3.conf
#    sudo tee "$CVMFS_TEST_S3_CONFIG" <<EOF
#CVMFS_S3_ACCESS_KEY=**UNUSED**
#CVMFS_S3_SECRET_KEY=**UNUSED**
#CVMFS_S3_HOST=$S3_HOST
#CVMFS_S3_PORT=$S3_PORT
#CVMFS_S3_REGION=auto
#CVMFS_S3_BUCKET=$CVMFS_TEST_REPO
#CVMFS_S3_X_AMZ_ACL=public-read
#CVMFS_S3_MAX_NUMBER_OF_PARALLEL_CONNECTIONS=64
#CVMFS_S3_DNS_BUCKETS=false
#CVMFS_S3_URI_SCHEME=http
#CVMFS_S3_PROXY=http://127.0.0.1:8088
#CVMFS_S3_MAX_RETRIES=1000
#EOF
#    source "$CVMFS_TEST_S3_CONFIG"
#    export CVMFS_TEST_S3_CONFIG # for graft-tests.py
#
#    sudo mkdir -p /var/http/root/"$CVMFS_TEST_REPO"/"$CVMFS_TEST_REPO"
#    sudo touch             /var/log/small-proxyd.log /var/log/small-httpd.log /var/log/gateway.log
#    sudo chown "$(whoami)" /var/log/small-proxyd.log /var/log/small-httpd.log /var/log/gateway.log
#    ! sudo fuser -n tcp 8088
#    sudo stdbuf -i0 -o0 -e0  "$this_script_dir"/opt/bin/proxy_server.py     |& sudo tee /var/log/small-proxyd.log &
#    ! sudo fuser -n tcp 8000
#    sudo stdbuf -i0 -o0 -e0  "$this_script_dir"/opt/bin/http_server.py 8000 |& sudo tee /var/log/small-httpd.log  &
#    for seconds in {1..10}; do
#        if http_ports_up; then break; fi
#        sleep 1
#    done
#    http_ports_up
fi

# gateway_up() {
#     sudo fuser -n tcp 4929
# }
# GW_SHOULD_RESTART_FILE=$(mktemp --suffix=.gw-should-restart.901-ingestsql.XXXXXXX)
# run_gateway() {
#     while [[ -f "$GW_SHOULD_RESTART_FILE" ]]; do
#         MAYBE_TRACER=''
#         RECEIVER=$(which cvmfs_receiver)
#         if [[ -v DEBUG ]]; then
#             MAYBE_TRACER=rr
#             RECEIVER="$this_script_dir/receiver-wrapper"
#         fi
#         sudo $MAYBE_TRACER cvmfs_gateway --access_config_file /etc/cvmfs/gateway/"$CVMFS_TEST_REPO"/repo.json --user_config_file /etc/cvmfs/gateway/"$CVMFS_TEST_REPO"/user.json --work_dir /var/lib/cvmfs-gateway/"$CVMFS_TEST_REPO" --receiver_path "$RECEIVER" |& sudo tee -a /var/log/gateway.log
#     done &
#     for seconds in {1..10}; do
# 	if gateway_up; then break; fi
# 	sleep 1
#     done
#     trap stop_gateway ERR
# }
# stop_gateway() {
#     rm "$GW_SHOULD_RESTART_FILE" || true
#     sudo killall cvmfs_gateway || true
#     while sudo pgrep cvmfs_gateway; do
# 	sleep 0.1
#     done
#     ! gateway_up
#     trap - ERR
# }

sudo sed -i /etc/cvmfs/gateway/user.json -e s/'"max_lease_time" : 7200,'/'"max_lease_time" : 60,'/
grep -q '"max_lease_time" : 60,' /etc/cvmfs/gateway/user.json
(
    source "$TEST_ROOT"/test_functions
    set_up_repository_gateway "$CVMFS_TEST_REPO" -o "$CVMFS_TEST_USER" -w "$CVMFS_TEST_HTTP_BASE" -s "$CVMFS_TEST_S3_CONFIG"
)
#sudo rsync -rtv "$this_script_dir"/etc/cvmfs/gateway  /etc/cvmfs
#sed "$this_script_dir"/etc/cvmfs/gateway/test.repo/repo.json.in \
#    -e "s#\$CVMFS_TEST_HTTP_BASE#$CVMFS_TEST_HTTP_BASE#" \
#    -e "s#\$CVMFS_TEST_REPO#$CVMFS_TEST_REPO#" \
#| sudo tee /etc/cvmfs/gateway/"$CVMFS_TEST_REPO"/repo.json

sudo rsync -rtv "$this_script_dir"/etc/cvmfs/config.d /etc/cvmfs
#sudo rsync -rtv "$this_script_dir"/etc/cvmfs-gateway-client  /etc
#! gateway_up
#touch "$GW_SHOULD_RESTART_FILE"
#run_gateway
#gateway_up


if ! grep '^user_allow_other' /etc/fuse.conf; then
    echo user_allow_other | sudo tee -a /etc/fuse.conf
fi

if [[ -v RECONSTRUCT_REPO ]]; then
    # This code is not executed by default.
    # This code is incomplete.
    # There is no code to reconstruct the files checked in graft-tests.py:do_file_read_test().
    # Works only under systemd.
    (
        source $TEST_ROOT/test_functions
        apache_switch on
    )

    #sudo cvmfs_server mkfs -o "$CVMFS_TEST_USER" -w "$CVMFS_TEST_HTTP_BASE" -s "$CVMFS_TEST_S3_CONFIG" "$CVMFS_TEST_REPO"
    sudo cp /etc/cvmfs/keys/"$CVMFS_TEST_REPO".pub /etc/cvmfs-gateway-client/"$CVMFS_TEST_REPO"/pubkey

    sudo cvmfs_server transaction "$MY_REPO"
    sudo mkdir -p /cvmfs/"$MY_REPO"/TEST_DIRECTORY/DIR{1,2,3}
    for subdir in . DIR{1,2,3}; do
        for file in /cvmfs/"$MY_REPO"/TEST_DIRECTORY/"$subdir"/file{1,2,3}; do
        echo OH HI | sudo tee "$file"
        done
    done
    sudo cvmfs_server publish "$MY_REPO"
    sudo cvmfs_config umount # or: fusermount -u /var/spool/cvmfs/"$MY_REPO"/rdonly
    sudo umount /cvmfs/$MY_REPO

else # ! [[ -v RECONSTRUCT_REPO ]]
    sudo touch /etc/fstab # absense of /etc/fstab on CentOS 9 containers breaks `cvmfs_server migrate`
    sudo mkdir -p /var/spool/cvmfs/"$CVMFS_TEST_REPO"
    sudo rsync -rtv "$this_script_dir"/var/spool/cvmfs/test.repo/{reflog.chksum,tmp}  /var/spool/cvmfs/"$CVMFS_TEST_REPO"
    #sudo mkdir -p /var/http/root/"$CVMFS_TEST_REPO"/
    #sudo rsync -rtv "$this_script_dir"/var/http/root/test.repo/test.repo/  /var/http/root/"$CVMFS_TEST_REPO"/"$CVMFS_TEST_REPO"
    if [[ "$S3_SERVER_PROVIDED" == 1 ]]; then
        pushd "$this_script_dir"/var/http/root/test.repo/
        find test.repo/ -type f -print0 | xargs --verbose -0 -I '{}' s3cmd put '{}' s3://"$CVMFS_S3_BUCKET"/'{}'
        popd
    fi
    sudo rsync -rtv "$this_script_dir"/etc/cvmfs/{repositories.d,keys}  /etc/cvmfs
    sudo tee -a /etc/cvmfs/repositories.d/"$CVMFS_TEST_REPO"/server.conf <<EOF
CVMFS_UPSTREAM_STORAGE=S3,/var/spool/cvmfs/$CVMFS_TEST_REPO/tmp,$CVMFS_TEST_REPO@$CVMFS_TEST_S3_CONFIG
CVMFS_STRATUM0=$CVMFS_TEST_HTTP_BASE/$CVMFS_TEST_REPO
CVMFS_SERVER_PROXY=DIRECT
EOF
    sudo tee -a /etc/cvmfs/repositories.d/"$CVMFS_TEST_REPO"/client.conf <<EOF
CVMFS_SERVER_URL=$CVMFS_TEST_HTTP_BASE/$CVMFS_TEST_REPO
CVMFS_EXTERNAL_URL=$CVMFS_TEST_HTTP_BASE/$CVMFS_TEST_REPO
CVMFS_HTTP_PROXY=DIRECT
EOF
    sudo tee -a /etc/cvmfs/config.d/"$CVMFS_TEST_REPO".local <<EOF
CVMFS_SERVER_URL=$CVMFS_TEST_HTTP_BASE/$CVMFS_TEST_REPO
CVMFS_EXTERNAL_URL=$CVMFS_TEST_HTTP_BASE/$CVMFS_TEST_REPO
CVMFS_HTTP_PROXY=DIRECT
EOF
    sudo /usr/lib/systemd/system-generators/systemd-fstab-generator /run/systemd/generator '' '' || true
    sudo systemctl daemon-reload
    sudo -E bash -x cvmfs_server resign "$CVMFS_TEST_REPO"
fi

sudo mkdir -p "$CVMFS_TEST_MOUNTPOINT"
# TODO The manifest file .cvmfspublished file contains test.repo as repo name, needs changing and re-signing for parametrized $CVMFS_TEST_REPO.
# Check that HTTP servers serve expected contents:
diff -Nurd "$this_script_dir"/var/http/root/test.repo/"$CVMFS_TEST_REPO"/.cvmfspublished <(curl --disable --verbose --fail "$CVMFS_TEST_HTTP_BASE"/$CVMFS_TEST_REPO/.cvmfspublished)
if [[ "$S3_SERVER_PROVIDED" == 0 ]]; then
    diff -Nurd "$this_script_dir"/var/http/root/test.repo/"$CVMFS_TEST_REPO"/.cvmfspublished <(curl --disable --verbose --fail --proxy http://localhost:8088 "$CVMFS_TEST_HTTP_BASE"/$CVMFS_TEST_REPO/.cvmfspublished)
fi

sudo "$CVMFS2" -d -o config=/etc/cvmfs/repositories.d/$CVMFS_TEST_REPO/client.conf,allow_other $CVMFS_TEST_REPO "$CVMFS_TEST_MOUNTPOINT" |& sudo tee -a /var/log/cvmfs2.log
attr -g revision "$CVMFS_TEST_MOUNTPOINT" # a check of mount success
ls -l "$CVMFS_TEST_MOUNTPOINT"
[[ -f "$CVMFS_TEST_MOUNTPOINT"/TEST_DIRECTORY/DIR1/file1 ]]

export PYTHONUNBUFFERED=1
#"$this_script_dir"/graft-tests.py --no-mount standard file-read |& tee /var/log/graft-tests.log

# Fix
# UnicodeEncodeError: 'ascii' codec can't encode characters...
# on Almalinux 8
export PYTHONIOENCODING=UTF-8
export LANG=C.UTF-8

sudo -E "$this_script_dir"/graft-tests.py --no-mount standard |& sudo tee /var/log/graft-tests.log
