#!/bin/bash
set -euo pipefail
set -x

this_script_dir=$(dirname "$(readlink -f "$0")")
if ! [[ -v TEST_ROOT ]]; then
    TEST_ROOT=$(readlink -f "$this_script_dir/../..")
fi
build_dir=$(dirname "$TEST_ROOT")

sudo mkdir -p /var/{spool,run}/cvmfs/
#[[ -d /etc/cvmfs/default.d ]]
#cat > /etc/cvmfs/default.d/99-test.conf <<EOF
#CVMFS_USER=$(whoami)
#CVMFS_HTTP_PROXY=DIRECT
#CVMFS_AUTO_UPDATE=yes
#CVMFS_USE_FILE_CHUNKING=false
#CVMFS_QUOTA_LIMIT=-1
#EOF
#export CVMFS_TEST_USER=$(whoami)

#rsyslogd &
#systemctl enable --now httpd

sudo rm -rf /var/spool/cvmfs/* # just in case
sudo cp -a /etc/fstab{,.orig}
sudo truncate --size=0 /etc/fstab

create_repo() {
	MOUNT_OPTS=$1
	EXTRA_CONFIG=$2
	export CVMFS_USE_FILE_CHUNKING=false
	sudo mv /etc/fstab{,.bkp}
	(
	    source $TEST_ROOT/test_functions
	    apache_switch on
	)
	sudo -E cvmfs_server mkfs -o "$CVMFS_TEST_USER" "$CVMFS_TEST_REPO"
	! grep CVMFS_ROOT_HASH /var/spool/cvmfs/"$CVMFS_TEST_REPO"/client.local
	export CVMFS_TEST_MOUNTPOINT=/cvmfs/$CVMFS_TEST_REPO
	cat "$CVMFS_TEST_MOUNTPOINT"/new_repository

	pgrep cvmfs2
	sudo umount /cvmfs/"$CVMFS_TEST_REPO"
	sudo umount /var/spool/cvmfs/"$CVMFS_TEST_REPO"/rdonly
	sudo sed -i /etc/fstab -e "s/,noauto /,simple_options_parsing,disable_watchdog,noauto,debug,$MOUNT_OPTS /"
	sudo mv /etc/fstab{,.new}
	cat /etc/fstab.new /etc/fstab.bkp | sudo tee /etc/fstab
	sudo systemctl daemon-reload
	sudo tee -a /etc/cvmfs/repositories.d/"$CVMFS_TEST_REPO"/client.conf <<-EOF
	CVMFS_HTTP_PROXY=DIRECT
	CVMFS_KCACHE_TIMEOUT=0
	CVMFS_MAX_TTL_SECS=1
	CVMFS_AUTO_UPDATE=yes
	CVMFS_DEBUGLOG=/var/log/$CVMFS_TEST_REPO.cvmfs-debug.log
	CVMFS_USYSLOG=/var/log/$CVMFS_TEST_REPO.cvmfs-usyslog.log
	$EXTRA_CONFIG
	EOF
	sudo tee -a /etc/cvmfs/repositories.d/"$CVMFS_TEST_REPO"/server.conf <<-EOF
	CVMFS_USE_FILE_CHUNKING=false
	CVMFS_QUOTA_LIMIT=-1
	EOF

	sudo mount  /var/spool/cvmfs/"$CVMFS_TEST_REPO"/rdonly
	sudo mount  /cvmfs/"$CVMFS_TEST_REPO"

	sudo -E cvmfs_server transaction "$CVMFS_TEST_REPO"
	find "$CVMFS_TEST_MOUNTPOINT"/ -mindepth 1 -print -delete

	COPY_WHAT=$(mktemp -d)
	test -d "$COPY_WHAT" # must be a dir
	! find "$COPY_WHAT" -mindepth 1 -type d # no subdirs
	sudo rsync --recursive --times --links --perms "$COPY_WHAT"/ "$CVMFS_TEST_MOUNTPOINT"

	time sudo -E cvmfs_server publish "$CVMFS_TEST_REPO"
	mount | grep "$CVMFS_TEST_REPO"

	if [[ -v DEBUG ]]; then
		sudo umount /cvmfs/"$CVMFS_TEST_REPO"
		sudo umount /var/spool/cvmfs/"$CVMFS_TEST_REPO"/rdonly
		nohup sudo valgrind \
			--tool=memcheck \
			--log-file=/var/log/"$CVMFS_TEST_REPO".valgrind.log \
			--enable-debuginfod=yes \
			--leak-check=full \
			--show-leak-kinds=all \
			--track-origins=yes \
			--trace-children=yes \
			--track-fds=yes \
			--show-error-list=all \
			--read-var-info=yes \
			--gen-suppressions=all \
			--suppressions=<(grep -v '^[=-]' "$build_dir"/valgrind.supp) \
			\
			/usr/bin/cvmfs2 -f -o \
			allow_other,fsname="$CVMFS_TEST_REPO",config=/etc/cvmfs/repositories.d/"$CVMFS_TEST_REPO"/client.conf:/var/spool/cvmfs/"$CVMFS_TEST_REPO"/client.local,disable_watchdog,simple_options_parsing,grab_mountpoint,uid=0,gid=0"$MOUNT_OPTS" \
			"$CVMFS_TEST_REPO" /var/spool/cvmfs/"$CVMFS_TEST_REPO"/rdonly \
			&
		while ! grep /var/spool/cvmfs/"$CVMFS_TEST_REPO"/rdonly /proc/mounts; do
			sleep 1
		done
		sudo mount /cvmfs/"$CVMFS_TEST_REPO"
	fi

	FRESH=$(cvmfs_talk -p /var/spool/cvmfs/"$CVMFS_TEST_REPO"/cvmfs_io internal affairs | grep 'cvmfs.n_fs_readdir_0_offset\>' | cut -d'|' -f 2)
	[[ "$FRESH" == 0 ]]
	ls "$CVMFS_TEST_MOUNTPOINT"
	AFTER_1_PASS=$(cvmfs_talk -p /var/spool/cvmfs/"$CVMFS_TEST_REPO"/cvmfs_io internal affairs | grep 'cvmfs.n_fs_readdir_0_offset\>' | cut -d'|' -f 2)
	[[ "$AFTER_1_PASS" == 1 ]]
	find "$CVMFS_TEST_MOUNTPOINT"
	AFTER_2_PASSES=$(cvmfs_talk -p /var/spool/cvmfs/"$CVMFS_TEST_REPO"/cvmfs_io internal affairs | grep 'cvmfs.n_fs_readdir_0_offset\>' | cut -d'|' -f 2)
	if [[ "$EXTRA_CONFIG" == 'CVMFS_FUSE_KEEP_DIR_CACHE=1' ]]; then
		[[ "$AFTER_2_PASSES" == 1 ]]
	else
		[[ "$AFTER_2_PASSES" == 2 ]]
	fi

	sudo umount /cvmfs/"$CVMFS_TEST_REPO"
	sudo umount /var/spool/cvmfs/"$CVMFS_TEST_REPO"/rdonly
}

export CVMFS_TEST_REPO=test.repo.readdir-normal
create_repo '' ''

export CVMFS_TEST_REPO=test.repo.readdir-cached
create_repo '' 'CVMFS_FUSE_KEEP_DIR_CACHE=1'
