# Stage 1: Builder
FROM fedora:42 AS builder

USER root

RUN dnf install -y \
        attr \
        autoconf \
        automake \
        awk \
        bzip2 \
        checkpolicy \
        cmake \
        cpio \
        findutils \
        fuse \
        fuse-common \
        fuse-devel \
        fuse-libs \
        fuse3-devel \
        fuse3-libs \
        gcc-c++ \
        git \
        golang \
        gzip \
        jemalloc \
        jemalloc-devel \
        libacl-devel \
        libattr-devel \
        libcap-devel \
        libuuid-devel \
        make \
        openssl-devel \
        patch \
        procps-ng \
        psmisc \
        python3 \
        python3-devel \
        python3-pip \
        python3-pylibacl \
        python3-requests \
        python3-setuptools \
        python3-xattr \
        rpm-build \
        selinux-policy-devel \
        selinux-policy-targeted \
        sqlite \
        unzip \
        valgrind-devel \
        zlib \
        zlib-devel \
        ;

# This is a workaround for a sudo error that started after an 
# upgrade to the build image. Similar to https://github.com/apptainer/apptainer/issues/2756 but not quite clear
RUN chmod 0400 /etc/shadow

RUN echo '%sftnight ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN useradd -m -s /bin/bash sftnight
USER sftnight

RUN mkdir -p /home/sftnight/buildpackage
RUN mkdir -p /home/sftnight/buildpackage_config
RUN mkdir -p /home/sftnight/cvmfs

# Copy the repo
COPY --chown=sftnight . /home/sftnight/cvmfs
RUN cd /home/sftnight/cvmfs; ./ci/build_package.sh $PWD $PWD/../buildpackage/ cvmfs
RUN cd /home/sftnight/cvmfs; ./ci/build_package.sh $PWD $PWD/../buildpackage_config/ cvmfs-config

# Stage 2: Final
FROM fedora:42

USER root

# cloudtest dependencies
RUN dnf install -y \
        attr \
        autoconf \
        autofs \
        automake \
        awk \
        bzip2 \
        cmake \
        cpio \
        findutils \
        fuse \
        fuse-common \
        fuse-libs \
        fuse3-libs \
        gcc-c++ \
        gdb \
        git \
        golang \
        gzip \
        jemalloc \
        jq \
        libacl \
        libattr \
        libcap \
        libuuid \
        lsof \
        make \
        nc \
        openssl \
        patch \
        procps-ng \
        psmisc \
        python3 \
        python3-flask \
        python3-mod_wsgi \
        python3-pylibacl \
        python3-requests \
        python3-setuptools \
        python3-xattr \
        rpm-build \
        rr \
        rsync \
        rsyslog \
        sqlite \
        strace \
        unzip \
        usbutils \
        valgrind \
        vim \
        zlib \
        ;

# This is a workaround for a sudo error that started after an 
# upgrade to the build image. Similar to https://github.com/apptainer/apptainer/issues/2756 but not quite clear
RUN chmod 0400 /etc/shadow

# Copy and install binaries from the builder stage
COPY --from=builder /home/sftnight/buildpackage/RPMS/x86_64/ /tmp/.
COPY --from=builder /home/sftnight/buildpackage_config/RPMS/noarch/ /tmp/.
RUN dnf -y install /tmp/*.rpm

# Create the sftnight user
RUN useradd -m -s /bin/bash sftnight
RUN echo '%sftnight ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

ENV USER sftnight

CMD ["/usr/sbin/init"]

